version: "3.9"

services:
  crawler:
    build: crawler
    container_name: newscorpus_crawler
    env_file:
      - .env
    volumes:
      - ./crawler:/code
      - crawler-bashhistory:/commandhistory # Persist bash history
    depends_on:
      - mongo
    command: tail -f /dev/null # keep shell attached

  mongo:
    image: mongo:4
    container_name: newscorpus_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - ./mongo_data:/data/db
    expose:
      - 27017
    ports:
      - "27019:27017" # Port 27019 is exposed in dev mode

volumes:
  crawler-bashhistory: